name: geo_env_hybrid
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - attr=2.5.1
  - aws-c-auth=0.9.1
  - aws-c-cal=0.9.10
  - aws-c-common=0.12.5
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.6
  - aws-c-http=0.10.7
  - aws-c-io=0.23.3
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.10.1
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.35.2
  - aws-sdk-cpp=1.11.606
  - azure-core-cpp=1.16.1
  - azure-identity-cpp=1.13.2
  - azure-storage-blobs-cpp=12.15.0
  - azure-storage-common-cpp=12.11.0
  - azure-storage-files-datalake-cpp=12.13.0
  - blosc=1.21.6
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.12.2
  - cairo=1.18.4
  - capnproto=1.2.0
  - cfitsio=4.6.3
  - cyrus-sasl=2.1.28
  - expat=2.7.3
  - fmt=12.0.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.14.1
  - freexl=2.0.0
  - geoalchemy2=0.18.1
  - geos=3.14.1
  - giflib=5.2.2
  - greenlet=3.2.4
  - hdf4=4.2.15
  - hdf5=1.14.6
  - icu=75.1
  - json-c=0.18
  - kealib=1.6.2
  - keyutils=1.6.3
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-aarch64=2.44
  - lerc=4.0.0
  - libabseil=20250512.1
  - libadbc-driver-manager=1.9.0
  - libaec=1.1.4
  - libarchive=3.8.2
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcrc32c=1.1.2
  - libcurl=8.17.0
  - libdeflate=1.25
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.3
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgdal=3.12.0
  - libgdal-adbc=3.12.0
  - libgdal-core=3.12.0
  - libgdal-fits=3.12.0
  - libgdal-grib=3.12.0
  - libgdal-hdf4=3.12.0
  - libgdal-hdf5=3.12.0
  - libgdal-jp2openjpeg=3.12.0
  - libgdal-kea=3.12.0
  - libgdal-netcdf=3.12.0
  - libgdal-pdf=3.12.0
  - libgdal-pg=3.12.0
  - libgdal-postgisraster=3.12.0
  - libgdal-tiledb=3.12.0
  - libgdal-xls=3.12.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.84.4
  - libgomp=15.2.0
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.73.1
  - libhwy=1.3.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - libjxl=0.11.1
  - libkml=1.3.0
  - libkrb5=1.21.3
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnetcdf=4.9.3
  - libnghttp2=1.67.0
  - libnsl=2.0.1
  - libpng=1.6.51
  - libpq=18.1
  - libprotobuf=6.31.1
  - libre2-11=2025.11.05
  - librttopo=1.1.0
  - libsodium=1.0.20
  - libspatialite=5.1.0
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.1
  - liburing=2.12
  - libuuid=2.41.2
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxml2-devel=2.15.1
  - libxslt=1.1.43
  - libzip=1.11.2
  - libzlib=1.3.1
  - lmdb=0.9.31
  - lz4-c=1.10.0
  - lzo=2.10
  - minizip=4.0.10
  - muparser=2.3.5
  - ncurses=6.5
  - nspr=4.38
  - nss=3.118
  - openjpeg=2.5.4
  - openldap=2.6.10
  - openssl=3.6.0
  - packaging=25.0
  - pcre2=10.46
  - pip=25.3
  - pixman=0.46.4
  - poppler=25.07.0
  - poppler-data=0.4.12
  - postgresql=18.1
  - proj=9.7.1
  - psycopg2=2.9.10
  - pthread-stubs=0.3
  - python=3.11.11
  - python_abi=3.11
  - re2=2025.11.05
  - readline=8.3
  - s2n=1.6.0
  - setuptools=80.9.0
  - snappy=1.2.2
  - spdlog=1.16.0
  - sqlalchemy=2.0.43
  - sqlite=3.51.0
  - tiledb=2.29.2
  - tk=8.6.15
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzcode=2025b
  - uriparser=0.9.8
  - wheel=0.45.1
  - xerces-c=3.3.0
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-xorgproto=2024.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - attrs==25.4.0
      - certifi==2025.11.12
      - click==8.3.1
      - click-plugins==1.1.1.2
      - cligj==0.7.2
      - fiona==1.10.1
      - geopandas==1.1.1
      - numpy==2.3.5
      - pandas==2.3.3
      - pyogrio==0.12.1
      - pyproj==3.7.2
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - shapely==2.1.2
      - six==1.17.0
      - tzdata==2025.2
prefix: /home/fedora/miniconda3/envs/geo_env_hybrid
